#!/usr/bin/env python3
"""
Generate SQL to backfill function_type from the lokale parquet file.

Reads the parquet, extracts source_id → lok_funkcja mapping,
and outputs a SQL file with batched UPDATE statements.

Usage:
  python3 scripts/generate_backfill_sql.py
  # Then copy the generated SQL into Supabase SQL Editor
"""

import os
from pathlib import Path
import pyarrow.parquet as pq
import pandas as pd

PARQUET_FILE = Path(__file__).parent.parent / "data" / "0_transakcje_ceny_lokale.parquet"
OUTPUT_FILE = Path(__file__).parent / "backfill_function_type.sql"
BATCH_SIZE = 500  # source_ids per UPDATE statement


def main():
    print(f"Reading parquet: {PARQUET_FILE}")
    pf = pq.ParquetFile(str(PARQUET_FILE))

    schema_names = [f.name for f in pf.schema_arrow]
    id_col = "tran_lokalny_id_iip" if "tran_lokalny_id_iip" in schema_names else "gid"
    print(f"  Using ID column: {id_col}")

    # Read only needed columns, plus teryt for filtering
    cols = [id_col, "lok_funkcja"]
    if "teryt" in schema_names:
        cols.append("teryt")
    table = pf.read(columns=cols)
    df = table.to_pandas()

    # Drop rows without function_type or source_id
    df = df.dropna(subset=[id_col, "lok_funkcja"])
    df = df[df["lok_funkcja"].str.strip() != ""]

    print(f"  Total rows with function_type: {len(df):,}")
    print(f"  All function_types: {df['lok_funkcja'].value_counts().to_dict()}")

    # Filter to Warsaw (teryt starts with "1465" = m.st. Warszawa)
    if "teryt" in df.columns:
        df_warsaw = df[df["teryt"].str.startswith("1465", na=False)]
        print(f"  Warsaw rows: {len(df_warsaw):,}")
        print(f"  Warsaw function_types: {df_warsaw['lok_funkcja'].value_counts().to_dict()}")
    else:
        df_warsaw = df
        print("  No teryt column — using all rows")

    # Group by function_type
    grouped = df_warsaw.groupby("lok_funkcja")[id_col].apply(list).to_dict()

    # Generate SQL
    lines = [
        "-- Backfill function_type from RCN parquet data",
        "-- Generated by scripts/generate_backfill_sql.py",
        f"-- Warsaw rows: {len(df_warsaw):,}",
        "",
    ]

    total_statements = 0
    for func_type, source_ids in sorted(grouped.items(), key=lambda x: -len(x[1])):
        source_ids = [str(sid) for sid in source_ids]
        lines.append(f"-- {func_type}: {len(source_ids):,} rows")

        # Split into batches
        for i in range(0, len(source_ids), BATCH_SIZE):
            batch = source_ids[i:i + BATCH_SIZE]
            # Escape single quotes in source_ids
            escaped = [sid.replace("'", "''") for sid in batch]
            ids_str = ", ".join(f"'{sid}'" for sid in escaped)
            lines.append(
                f"UPDATE transactions SET function_type = '{func_type}' "
                f"WHERE source_id IN ({ids_str});"
            )
            total_statements += 1

        lines.append("")

    # Write to file
    sql = "\n".join(lines)
    OUTPUT_FILE.write_text(sql)
    file_size_mb = len(sql.encode()) / 1024 / 1024

    print(f"\nGenerated: {OUTPUT_FILE}")
    print(f"  Size: {file_size_mb:.1f} MB")
    print(f"  UPDATE statements: {total_statements}")
    print(f"  Function types: {list(grouped.keys())}")

    # If file is too large, split into separate files per function_type
    if file_size_mb > 5:
        print(f"\n  File is large ({file_size_mb:.1f} MB). Splitting by function_type...")
        for func_type, source_ids in grouped.items():
            source_ids = [str(sid) for sid in source_ids]
            part_lines = [f"-- Backfill function_type = '{func_type}' ({len(source_ids):,} rows)", ""]
            for i in range(0, len(source_ids), BATCH_SIZE):
                batch = source_ids[i:i + BATCH_SIZE]
                escaped = [sid.replace("'", "''") for sid in batch]
                ids_str = ", ".join(f"'{sid}'" for sid in escaped)
                part_lines.append(
                    f"UPDATE transactions SET function_type = '{func_type}' "
                    f"WHERE source_id IN ({ids_str});"
                )
            part_file = OUTPUT_FILE.with_name(f"backfill_{func_type}.sql")
            part_file.write_text("\n".join(part_lines))
            part_size = len("\n".join(part_lines).encode()) / 1024 / 1024
            print(f"    {part_file.name}: {part_size:.1f} MB")


if __name__ == "__main__":
    main()
